version: '3'
services:

  db:
    build: docker/db
    volumes:
      - tf-hub-db-data:/var/lib/mysql
    ports:
      - 3310:3306
    environment:
      - MYSQL_ROOT_PASSWORD=devdatabase
      - MYSQL_DATABASE=tfhub

volumes:
  tf-hub-db-data:
