version: '3'
services:
  app:
    build: docker/app
    ports:
      - 127.0.0.1:3333:3333
      - 9229:9229
    depends_on:
      - db
    volumes:
      - .:/app
  db:
    image: mysql:5.7.22
    volumes:
      - tom-dashboard-db-data:/var/lib/mysql
    ports:
      - 3310:3306
    environment:
      - MYSQL_ROOT_PASSWORD=devdatabase
      - MYSQL_DATABASE=tomdashboard

volumes:
  tom-dashboard-db-data:
