definitions:
  Project:
    type: object
    properties:
      id:
        type: integer
      description:
        type: string
      is_active:
        type: boolean
      meeting_time_id:
        type: integer
      slack_channel_id:
        type: string
